# Site settings
title: AngularJS México
email: josue.ggh@gmail.com
description: "En AngularJS México encontrarás la información de todos los meetups del país. Actualmente en Ciudad de México, Guadalara y Querétaro."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://angularjsmexico.com" # the base hostname & protocol for your site
twitter_username: angularjsmexico
github_username:  jekyll

# Build settings
markdown: kramdown
